/** Contextual, genre-neutral engineering guidance. Never a promise of automated perfection. */
import { fileURLToPath } from 'node:url'
export const BUILD_PROTOCOL_TEXT = 'قبل البناء استخدم game_build_guide لتحديد المحرك والأبعاد والأجهزة المستهدفة ومعايير القبول بحسب طلب العميل، ولا تفرض نوع لعبة أو شخصية أو كاميرا أو سلاحاً. افحص النسخة المثبتة، افصل الإدخال والفيزياء والتحريك والكاميرا، وحافظ على الأصول والهياكل العظمية. اختبر Godot عبر godot_verify ثم اختبر العرض والتحكم فعلياً؛ وللويب استخدم game_playtest باختبارات حالة صريحة وبملفات أجهزة desktop/mobile/tablet حسب المطلوب. لا تعتبر فتح المشروع أو تغير الصورة أو عدد FPS على محاكاة برمجية دليلاً على اكتمال اللعبة أو أدائها على جهاز حقيقي. لا تلمس مشاريع أخرى.'

export function buildGameGuide(engine: string, dimension: string, platforms: string[], genre = '') {
  if (!['godot', 'three', 'blender'].includes(engine)) throw new Error('engine must be godot, three or blender')
  if (!['2d', '3d'].includes(dimension)) throw new Error('dimension must be 2d or 3d')
  if (!Array.isArray(platforms) || platforms.length === 0 || platforms.some(p => !['desktop', 'mobile', 'tablet', 'web'].includes(p))) throw new Error('Choose target platforms: desktop, mobile, tablet, web')
  const touch = platforms.some(p => p === 'mobile' || p === 'tablet')
  return {
    engine, dimension, platforms: [...new Set(platforms)], genre: genre || 'Not specified — infer from the request or ask; do not default to a shooter',
    status: 'planning guidance, not implementation or certification',
    resources: { engineering: fileURLToPath(new URL('../guides/game-engineering.md', import.meta.url)), capabilities: engine === 'godot' ? fileURLToPath(new URL('../../godot/GODOT-CAPABILITIES.md', import.meta.url)) : engine === 'three' ? fileURLToPath(new URL('../../three/CAPABILITIES.md', import.meta.url)) : null },
    preserve: ['Do not change other projects or delete assets to hide performance problems.', 'Respect client feature removals, art direction, reference approval and local-first assets.', 'Choose camera, controls, movement model and units for this game; human-scale characters are not universal.'],
    architecture: ['Separate input intent, fixed-step physics, animation state, camera presentation and UI.', 'Define input actions, collision layers/masks, coordinate axes, units and acceptance tests before coding.', 'Build a minimal playable slice with actual world/content first; increase scale only after validation.'],
    physics: ['Fixed physics step with bounded catch-up; clamp huge elapsed time after tab resume.', 'Normalize diagonal movement; apply velocity in units/second. Do not multiply displacement by delta twice.', 'One motion authority per body: physics velocity OR root motion, never competing position writes.', 'Test floor contact, slopes, steps, corners, spawn clearance, high-speed tunneling and camera obstruction.', 'Concave triangle collision is for static level geometry; moving bodies need supported primitive/convex shapes.'],
    animation_camera: ['Preserve skeleton hierarchy, rest pose, weights, actions, morph targets and animation names on export.', 'Choose acceleration, braking, turn rate and animation blending for the requested character/vehicle/style.', 'Drive locomotion blend from measured velocity; prevent foot sliding by matching clip speed and controller speed.', 'Apply yaw/pitch limits only to camera models that need them; avoid roll, bob and shake unless requested.', 'Use frame-rate independent smoothing: weight = 1 - exp(-response * dt); test occlusion and FOV/aspect changes.'],
    input: touch ? ['Use action-based keyboard/gamepad and touch adapters, not separate game logic.', 'Track independent pointer/touch IDs for move and look. Handle pointercancel, focus loss, pause and touch release.', 'Test multi-touch, dead zones, safe areas, orientation changes and large usable controls; pointer lock is desktop-only.', 'Provide sensitivity and inverted-look options when relevant; do not assume a virtual joystick suits every genre.'] : ['Use remappable actions and focus/pause release. Verify keyboard and optional gamepad bindings.', 'Choose cursor, drag, pointer lock or direct touch according to the game, not a fixed template.'],
    engine_notes: engine === 'godot' ? ['Detect installed Godot 4.x version and supported renderer/export templates, rather than hard-code an API version.', 'CharacterBody2D/3D movement belongs in _physics_process; set velocity then move_and_slide. Never bypass collisions with unconditional position writes.', 'Use AnimationTree/AnimationPlayer deliberately. Use SpringArm3D or a tested shape cast only for cameras that need occlusion.', 'Run godot_verify import + at least 240 frames; then verify the real viewport, active camera, content, physics and input. Headless success alone cannot prove them.'] : engine === 'three' ? ['Three.js is a renderer, not a physics engine. Select a suitable collision/physics layer only when the game requires it.', 'Use local pinned imports; await glTF/decoder loading; expose visible recoverable errors and retry paths.', 'Use a fixed-step physics accumulator and interpolate presentation. Update camera aspect/projection and renderer size on resize.', 'Dispose owned geometries/materials/textures, controls, observers and animation loops on teardown; cap pixel ratio by measured device budget.'] : ['Use bpy in a factory-startup session with explicit active object/mode/selection and absolute output paths.', 'Use whole-asset transforms through a stable root; validate exported bounds and pivot in the target engine.', 'Do not decimate skinned/morph meshes blindly. Preserve rig/action data and validate animation after GLB re-import.'],
    acceptance: ['Log engine/library versions, selected scope and controls.', 'Verify travel distance and stopping at multiple render rates; compare against expected units/second.', 'Assert gameplay state changes from real input (movement, turn, interaction or another genre-appropriate action), not screenshot bytes.', 'Verify camera-visible content, collision, reset/respawn and at least one failure path.', 'Record physical-device performance separately from software-rendered browser emulation.'],
    device_matrix: platforms.map(platform => ({ platform, required: platform === 'web' ? 'Browser export, HTTP serving, WebGL/renderer support, audio unlock, focus recovery, CORS and asset failure handling' : platform === 'desktop' ? 'Keyboard/mouse, optional gamepad, resize, pause/resume and intended graphics budget' : 'Touch/multi-touch, orientation, safe area, UI scale, memory budget and a real representative device', verified: false })),
    gates: engine === 'godot' ? ['godot_verify', 'real viewport/input test', 'export + device test for each requested target'] : engine === 'three' ? ['game_playtest with explicit hud_checks/state expressions and device profile', 'real device performance + touch test'] : ['blender_code', 'asset_pipeline or rig-aware export', 'target-engine re-import check'],
    limitations: ['No tool can certify arbitrary commands or human-quality art/animation at 100%.', 'Native mobile exports require the relevant SDKs, signing and installed templates; browser emulation is not hardware testing.'],
  }
}
